# Generated by Django 2.0.4 on 2018-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180417_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='url',
            field=models.TextField(default='http://www.3ds.com'),
            preserve_default=False,
        ),
    ]
